apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.11.0-rc1/manifests/install.yaml

## changes to config maps
patchesStrategicMerge:
  - argocd_cmd_params_cm_patch.yml

namespace: argocd
