---
- name: Install Java 17 Ubuntu
  hosts: Ubuntu
  become: true
  tasks:

    # curl 커맨드 설치
    - name: Install curl
      apt:
        name: curl
        state: present

    # java 17 Debian 리눅스용 패키지 레포 등록
    - name: Download Java 17 Debian package
      shell: wget --no-check-certificate -O /tmp/jdk-17_linux-x64_bin.deb "https://download.java.net/java/17/latest/jdk-17_linux-x64_bin.deb"
    
    # apt 업데이트
    - name: Update apt packages
      apt:
        update_cache: yes
        
    # java 17 Debian 패키지 인스톨
    - name: Install Java 17 Debian package
      apt:
        deb: "/tmp/jdk-17_linux-x64_bin.deb"
        state: present