---
- name: Install Java 17 CentOS 7/RHEL
  hosts: all
  become: true
  tasks:

    # 자바 17 레포지토리 등록
    - name: Download Java 17 RPM package
      get_url:
        url: "https://download.java.net/java/17/latest/jdk-17_linux-x64_bin.rpm"
        dest: "/tmp/jdk-17_linux-x64_bin.rpm"
    
    # 자바 17 인스톨
    - name: Install Java 17 RPM package
      yum:
        name: "/tmp/jdk-17_linux-x64_bin.rpm"
        state: present