---
- name: Install MySQL Community Server
  hosts: localhost
  become: yes
  tasks:

    # curl 커맨드 설치   
    - name: Install curl
      apt:
        name: curl
        state: present

    # mysql server 패키지 curl
    - name: Download MySQL Community Server packages
      get_url:
        url: "https://dev.mysql.com/get/mysql80-community-release-el8-8.noarch.rpm"
        dest: "/tmp/mysql80-community-release-el8-8.noarch.rpm"
 
    # mysql 커뮤니티 설치 
    - name: Install MySQL Community Server repository
      yum:
        name: "/tmp/mysql80-community-release-el8-8.noarch.rpm"
        state: present

    # mysql 서버 패키지 설치
    - name: Install MySQL Community Server packages
      yum:
        name:
          - mysql-community-common-8.2.0-1.el8.x86_64.rpm
          - mysql-community-client-plugins-8.2.0-1.el8.x86_64.rpm
          - mysql-community-libs-8.2.0-1.el8.x86_64.rpm
          - mysql-community-devel-8.2.0-1.el8.x86_64.rpm
          - mysql-community-icu-data-files-8.2.0-1.el8.x86_64.rpm
          - mysql-community-client-8.2.0-1.el8.x86_64.rpm
          - mysql-community-server-8.2.0-1.el8.x86_64.rpm
        state: present
        
    # MySQL 서버 시작
    - name: Initialize MySQL Server
      command: sudo mysqld --defaults-file=/etc/my.cnf --initialize-insecure
      become: yes
      
    # MySQL 방화벽 허용
    - name: Add MySQL service to firewall
      firewalld:
        service: mysql
        state: enabled
        immediate: yes