---
- name: Configure MySQL Docker container
  hosts: ec2-user
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    # url 라이브러리3 설치
    - name: Install urllib3 version 1.26.8
      pip:
        name: urllib3==1.26.8
        
    # docker전용 python 라이브러리 설치
    - name: docker-py install
      pip:
        name: docker-py
        executable: pip3

    # mysql 도커 컨테이너 다운로드 및 설치
    - name: Run MySQL Docker container
      docker_container:
        name: mysqldb
        image: mrsono0/mysql_5.7
        state: started
        restart_policy: always
        env:
          MYSQL_ROOT_PASSWORD: education
          MYSQL_DATABASE: guestbook
        ports:
          - "3306:3306"