---
- hosts: all
  become: yes
  tasks:

    # yum-utils 인스톨
    - name: "Installing yum-utils"
      yum:
        name:
          - yum-utils
        state: latest

     # amazon-linux-extras docker version 사용 설정  
    - name: "amazon-linux-extras Docker repo enable"
      command: amazon-linux-extras enable docker
      changed_when: false

    # docker latest 버전 설치
    - name: "Installing Docker latest version"
      yum:
        name: docker
        state: present

    # docker 시작, docker 시작프로그램 등록
    - name: "Starting and Enabling Docker service"
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add jenkins user to docker group
      user:
        name: jenkins
        groups: docker
        append: yes

    # Jenkins 사용환경을 위한 docker group 추가 설정
    - name: Add jenkins user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes