apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - argocd-server-ingress.yaml
patchesStrategicMerge:
  - argocd_cmd_params-cm.yaml