---
- name: Install Jenkins on Ubuntu 
  hosts: tag_OS_ubuntu
  become: true
  tasks:
  
    # apt 인증서 패키지 설치
    - name: Install ca-certificates package
      apt:
        name: ca-certificates
        state: present

    # curl 커맨드 설치 
    - name: Install curl
      apt:
        name: curl
        state: present

    # apt 패키지 업데이트
    - name: Update apt packages
      apt:
        update_cache: yes

    # Jenkins GPG 키 추가
    - name: Add Jenkins GPG key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 5BA31D57EF5975CA
        state: present

    # jenkins 레포지토리 등록
    - name: Add Jenkins repository
      apt_repository:
        repo: deb http://pkg.jenkins.io/debian-stable binary/
        state: present
        filename: jenkins

    # 젠킨스 실행에 필요한 fontconfig 패키지 설치
    - name: Install fontconfig
      apt:
        name: fontconfig
        state: present

    # 젠킨스 설치
    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    # 젠킨스 실행 후 enable 설정
    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes

    # 젠킨스 초기 관리자 비밀번호 표시
    - name: Show Jenkins initialAdminPassword
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: shell_output

    # 콘솔에 초기 관리자 비밀번호 출력
    - name: Print to console 
      debug: 
        msg: "{{ shell_output.stdout }}"